export const USER_LOGIN_REQUEST = "USER_LOGI_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGI_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGI_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
